# Версия для старых докеров
#version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: containerbackend1
    restart: unless-stopped
    networks:
      - efmobilenetwork
    expose:
      - "8080"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s


  nginx:
    build:
      context: ./nginx
    container_name: nginx-container2
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - efmobilenetwork

networks:
  efmobilenetwork:
    driver: bridge
    name: efmobilenetwork

# если сеть уже существует
#networks:
#  efmobilenetwork:
#    external: true